services:

  postgres:
    image: postgres:16
    container_name: freshcart-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: freshcart
      POSTGRES_PASSWORD: freshcart
      POSTGRES_DB: freshcart

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./checkout-api/db/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - freshcart-network


  checkout-api:
    build:
      context: ./checkout-api

    image: checkout-api:latest

    container_name: checkout-api

    restart: unless-stopped

    depends_on:
      - postgres

    environment:
      DATABASE_URL: postgres://freshcart:freshcart@postgres:5432/freshcart

    ports:
      - "3001:3000"

    networks:
      - freshcart-network


  storefront:
    build:
      context: ./storefront

    image: storefront:latest

    container_name: storefront

    depends_on:
      - checkout-api

    restart: unless-stopped

    ports:
      - "8080:80"

    networks:
      - freshcart-network


volumes:
  postgres-data:

networks:
  freshcart-network:
